server:
  port: 8080

spring:
  application:
    name: SpaceLab-Java
  datasource:
    url: jdbc:postgresql://postgresql_slj:5432/spacelab_java
    username: avada_slj
    password: WddnZNCCgfA4YEu
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB
